language: go
go:
- 1.7.x

node_js:
  - "node"

before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

cache:
  directories:
  - $HOME/.cache/yarn

install:
- "curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -"
- "sudo apt-get install -y nodejs"

script: make all

notifications:
  email: false
  slack:
    secure: mWm58R+UK9pRhyERlSS3Dezxec+vFq9YPtpy4gpPQbAZA5zeZdAhGKj65NBcDFEYyXnGxIymbA0ZRZ4MVub7hLU0bvFS+VQyTGAwADQFgOl0rku7uLmdWrA2vBZBt1AkAQejYYFsG/No9KCDGw40W3su2llzfWqxrh5Tw8XxSTZfo3yytBcTqyxV6mouqsm407/Hv81tU06Cudgn43b5KYNagjjzYj5yI0xBC0DANK0ywEqJ0VE2hpCvhZpFRgjeIJSqvlt8KnBFzip8DwNUzJ4blXVHQILOqNt0PaaxeQ18IsKL7ug2WqegDuHOhBpNF5ITUqpTF4W4gNwzgM3QVQH2xE64bkKKuRE7lEHJ0xNtWkMU8dNSS+B6CP/D+4A4TgCf6V/pUSbiTct/NYGzcVC7HmNnlcaBL60HMum0CECy10Ba2EnfexB8CtHCDneKzy5TsdR18DwVQvVfdDHX7CpLE5C5ISO35+M2mWS1orIOtUTKC++6L4qWTwWm4rqkPGaRP3aQwlN3NhRJi6oJzd9wTfqQFuORsJKtm3vaAmW19zFuxxUEFYwqQwBELGgvf2kAgqbbnspcqlZlD4XteZX4e7//oQ51uhJXezasGzzP+LNrK5NMOU1x3dXGMHvOb1pV+LltPQxSxg6xCFS3Q7u3flmQ6rNuH/qZXwyAGX4=
